# Generated by Django 4.1.7 on 2023-03-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("short_description", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("image", models.ImageField(upload_to="projects/")),
                ("long_description", models.TextField()),
            ],
        ),
    ]
