version: "3.9"

services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass redis
    volumes:
      - redis_data:/data
    expose:
      - 6379
    depends_on:
      - db

volumes:
  static:
  media:
  db_data:
  redis_data:
