version: "3.9"

services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - REDIS_URL=redis://default:redis@redis:6379/0
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass redis
    volumes:
      - redis_data:/data
    expose:
      - 6379
    depends_on:
      - db

volumes:
  static:
  media:
  db_data:
  redis_data:
