# Generated by Django 4.1.7 on 2023-03-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="contact email"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="name"
            ),
        ),
    ]
