# Generated by Django 4.1.7 on 2023-03-29 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_customuser_social_links_sociallink_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sociallink",
            name="user",
        ),
    ]
