# Generated by Django 4.1.7 on 2023-03-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="titulation",
            name="start_date",
            field=models.DateField(),
        ),
    ]
