# Generated by Django 4.1.7 on 2023-03-27 16:25

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="technologies",
        ),
        migrations.AddField(
            model_name="skill",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.DeleteModel(
            name="Technology",
        ),
    ]
